
## Enter the two DEMs path for the comparison and the layout path to print the two river networks. 
dem_1 : C:\Users\abfernan\CrossCanFloodMapping\SResDEM\Data\HamiltonNiagara\StudyCase\Niagara_HRDTM_8m.tif
dem_2 : C:\Users\abfernan\CrossCanFloodMapping\SResDEM\Data\HamiltonNiagara\StudyCase\Niagara_SRDEM_8m.tif
layOutOutputPath : C:\Users\abfernan\CrossCanFloodMapping\SResDEM\Data\HamiltonNiagara\StudyCase\RiverNetworkOverlap.png

# Enter the path to the csv file contining the list of urls to download. It can contain one or more url. If multiples tiles are downloaded, the algorith will produce a mosaic with the specified <out_resolution>.
csv_demList : 
out_resolution : 8
