## Enter the two DEMs path for the comparison and the layout path to print the two river networks. 
dem_1 : C:\Users\abfernan\CrossCanFloodMapping\SResDEM\Data\Analyses1\cdem_clip_1\cdem16mvs8m\cdem16mVs8mDownHalf\cdem-canada-dem-clip-3979-1_LowerHalf.tif # Reference
dem_2 : C:\Users\abfernan\CrossCanFloodMapping\SResDEM\Data\Analyses1\cdem_clip_1\cdem16mvs8m\cdem16mVs8mDownHalf\SRDEM_x2_256_to_512_full_DSM_DTM_cleaned_cdem-canada-dem-clip-3979-1_LowerHalf.tif #S_Resolved
layOutOutputPath : C:\Users\abfernan\CrossCanFloodMapping\SResDEM\Data\Analyses1\cdem_clip_1\cdem16mvs8m\cdem16mVs8mDownHalf\riverNet3thOrd.png

# Enter the path to the csv file contining the list of urls to download. It can contain one or more url. If multiples tiles are downloaded, the algorith will produce a mosaic with the specified <out_resolution>.
csv_demList : ''
csvColumn : ''
out_resolution : 8
wporking_dir : .\data